# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jounghoolee/alveoServer/Xilinx/PynqDeepDive/final_project/final_project.srcs/sources_1/bd/vector_add_1/ip/vector_add_1_xbar_5/vector_add_1_xbar_5.xci
# IP: The module: 'vector_add_1_xbar_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jounghoolee/alveoServer/Xilinx/PynqDeepDive/final_project/final_project.srcs/sources_1/bd/vector_add_1/ip/vector_add_1_xbar_5/vector_add_1_xbar_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vector_add_1_xbar_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/jounghoolee/alveoServer/Xilinx/PynqDeepDive/final_project/final_project.srcs/sources_1/bd/vector_add_1/ip/vector_add_1_xbar_5/vector_add_1_xbar_5.xci
# IP: The module: 'vector_add_1_xbar_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jounghoolee/alveoServer/Xilinx/PynqDeepDive/final_project/final_project.srcs/sources_1/bd/vector_add_1/ip/vector_add_1_xbar_5/vector_add_1_xbar_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vector_add_1_xbar_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
