# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/vector_add_1/vector_add_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1 || ORIG_REF_NAME==vector_add_1} -quiet] -quiet

# IP: bd/vector_add_1/ip/vector_add_1_processing_system7_0_0/vector_add_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1_processing_system7_0_0 || ORIG_REF_NAME==vector_add_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/vector_add_1/ip/vector_add_1_mult_constant_0_0/vector_add_1_mult_constant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1_mult_constant_0_0 || ORIG_REF_NAME==vector_add_1_mult_constant_0_0} -quiet] -quiet

# IP: bd/vector_add_1/ip/vector_add_1_axi_dma_0_0/vector_add_1_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1_axi_dma_0_0 || ORIG_REF_NAME==vector_add_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/vector_add_1/ip/vector_add_1_axis_broadcaster_0_1/vector_add_1_axis_broadcaster_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1_axis_broadcaster_0_1 || ORIG_REF_NAME==vector_add_1_axis_broadcaster_0_1} -quiet] -quiet

# IP: bd/vector_add_1/ip/vector_add_1_axis_broadcaster_A_0/vector_add_1_axis_broadcaster_A_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1_axis_broadcaster_A_0 || ORIG_REF_NAME==vector_add_1_axis_broadcaster_A_0} -quiet] -quiet

# IP: bd/vector_add_1/ip/vector_add_1_vector_add_dma_A_0/vector_add_1_vector_add_dma_A_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1_vector_add_dma_A_0 || ORIG_REF_NAME==vector_add_1_vector_add_dma_A_0} -quiet] -quiet

# IP: bd/vector_add_1/ip/vector_add_1_axis_combiner_0_0/vector_add_1_axis_combiner_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1_axis_combiner_0_0 || ORIG_REF_NAME==vector_add_1_axis_combiner_0_0} -quiet] -quiet

# IP: bd/vector_add_1/ip/vector_add_1_rst_ps7_0_100M_1/vector_add_1_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1_rst_ps7_0_100M_1 || ORIG_REF_NAME==vector_add_1_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/vector_add_1/ip/vector_add_1_xbar_5/vector_add_1_xbar_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1_xbar_5 || ORIG_REF_NAME==vector_add_1_xbar_5} -quiet] -quiet

# IP: bd/vector_add_1/ip/vector_add_1_auto_ds_0/vector_add_1_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1_auto_ds_0 || ORIG_REF_NAME==vector_add_1_auto_ds_0} -quiet] -quiet

# IP: bd/vector_add_1/ip/vector_add_1_auto_pc_2/vector_add_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1_auto_pc_2 || ORIG_REF_NAME==vector_add_1_auto_pc_2} -quiet] -quiet

# IP: bd/vector_add_1/ip/vector_add_1_axi_mem_intercon_2/vector_add_1_axi_mem_intercon_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1_axi_mem_intercon_2 || ORIG_REF_NAME==vector_add_1_axi_mem_intercon_2} -quiet] -quiet

# IP: bd/vector_add_1/ip/vector_add_1_xbar_4/vector_add_1_xbar_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1_xbar_4 || ORIG_REF_NAME==vector_add_1_xbar_4} -quiet] -quiet

# IP: bd/vector_add_1/ip/vector_add_1_auto_pc_3/vector_add_1_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1_auto_pc_3 || ORIG_REF_NAME==vector_add_1_auto_pc_3} -quiet] -quiet

# IP: bd/vector_add_1/ip/vector_add_1_ps7_0_axi_periph_2/vector_add_1_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_add_1_ps7_0_axi_periph_2 || ORIG_REF_NAME==vector_add_1_ps7_0_axi_periph_2} -quiet] -quiet

# XDC: bd/vector_add_1/vector_add_1_ooc.xdc
